### ISSUE TITLE
Grafana doesn't start in RHEL 7

### ISSUE THREAD

**Issue by suckatrash** [puppetlabs/puppetlabs-pe_metrics_dashboard#12]
From /var/log/grafana/grafana.log:

```
t=2017-10-16T15:27:57-0700 lvl=eror msg="Failed to verify pid directory" logger=server error="mkdir /var/run/grafana: permission denied"
```

https://github.com/grafana/grafana/issues/4446

**Comment by suckatrash** [comment]
Should be able to close this now

**Comment by kamrankausar** [comment]
t=2018-07-02T09:49:13+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning="
t=2018-07-02T09:49:13+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2018-07-02T09:49:13+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2018-07-02T09:49:13+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2018-07-02T09:49:13+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2018-07-02T09:49:13+0000 lvl=info msg="Path Provisioning" logger=settings path=/usr/share/grafana
t=2018-07-02T09:49:13+0000 lvl=info msg="App mode production" logger=settings
t=2018-07-02T09:49:13+0000 lvl=eror msg="Failed to verify pid directory" logger=server error="mkdir /var/run/grafana-server: permission denied"
^C

**Comment by suckatrash** [comment]
Hi @kamrankausar, this project was moved to https://github.com/puppetlabs/puppet_metrics_dashboard so that we could release it to the forge: https://forge.puppet.com/puppetlabs/puppet_metrics_dashboard

I also merged a fix related to this issue today.  Could you see if the latest release of the new project (1.0.1) still exhibits this issue?
