### ISSUE TITLE
Grafana runs as non-root and can't bind to port 443 when SSL is used

### ISSUE THREAD

**Issue by suckatrash** [puppetlabs/puppetlabs-pe_metrics_dashboard#30]
Need to come up with a way for the service to bind to 443

```
t=2017-12-15T10:48:43-0800 lvl=eror msg="Fail to start server" logger=server error="listen tcp 0.0.0.0:443: bind: permission denied"
t=2017-12-15T10:48:43-0800 lvl=info msg="Shutdown started" logger=server code=1 reason="Startup failed"
```

**Comment by jarretlavallee** [comment]
From http://docs.grafana.org/installation/configuration/#http-port:

`setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server` should allow the service to bind to privileged ports.

**Comment by suckatrash** [comment]
I think we should document that the grafana service will not be able to bind to privileged ports and leave implementation to the user if they want to either allow the binary as in the method above or put a proxy service in front of it.

**Comment by HimanshuPant** [comment]
setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server  worked for me
